# Generated by Django 2.2.7 on 2019-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200)),
                ('got_us_throught', models.CharField(choices=[(1, 'SEARCH ENGINE'), (2, 'ADVERTISEMENT'), (3, 'OTHERS'), (0, 'fFEINDS')], default=3, max_length=200)),
                ('new_letter', models.IntegerField(default=0)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Customer contact',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Contacmodel',
        ),
    ]
