# Generated by Django 2.2.7 on 2019-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayden', '0006_auto_20191112_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='got_us_throught',
            field=models.CharField(choices=[('N', 'NEWS LETTER'), ('O', 'OTHERS'), ('A', 'ADVERTISEMENT'), ('f', 'FRIENDS'), ('S', 'SEARCH ENGINE')], default=3, max_length=200),
        ),
    ]
