# Generated by Django 2.2.7 on 2019-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayden', '0007_auto_20191112_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='got_us_throught',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='got_us_through',
            field=models.CharField(choices=[('A', 'ADVERTISEMENT'), ('O', 'OTHERS'), ('f', 'FRIENDS'), ('N', 'NEWS LETTER'), ('S', 'SEARCH ENGINE')], default=3, max_length=200),
        ),
    ]
