# Generated by Django 2.2.7 on 2019-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayden', '0008_auto_20191112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='got_us_through',
            field=models.CharField(choices=[('S', 'SEARCH ENGINE'), ('N', 'NEWS LETTER'), ('f', 'FRIENDS'), ('A', 'ADVERTISEMENT'), ('O', 'OTHERS')], default=3, max_length=200),
        ),
    ]
